services:
  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_injection_db
      MYSQL_USER: lab_user
      MYSQL_PASSWORD: lab_password
    volumes:
      - ./db/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/02_secure_user.sql:/docker-entrypoint-initdb.d/02_secure_user.sql
    networks:
      - lab-network

  app-vulnerabile:
    build: ./app/vulnerabile
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - lab-network

  app-sicura:
    build: ./app/sicura
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
