services:
  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_injection_db
      MYSQL_USER: lab_user
      MYSQL_PASSWORD: lab_password
    volumes:
      - ./db/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/02_secure_user.sql:/docker-entrypoint-initdb.d/02_secure_user.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - lab-network

  app-vulnerabile:
    build: ./app/vulnerabile
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lab-network

  app-sicura:
    build: ./app/sicura
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./audit.log:/var/www/html/audit.log
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge

